<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Your_mark_model extends yidas\Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get your_mark by id
     */
    function get_your_mark($id)
    {
        return $this->db->get_where('your_mark',array('id'=>$id))->row_array();
    }
    
    /*
     * Get your_mark by id
     */
    function get_your_mark_by_client_id($client_id)
    {
        return $this->db->get_where('your_mark',array('client_id'=>$client_id))->row_array();
    }
        
    /*
     * Get all your_marks
     */
    function get_all_your_marks()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('your_mark')->result_array();
    }
        
    /*
     * function to add new your_mark
     */
    function add_your_mark($params)
    {
        $this->db->insert('your_mark',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update your_mark
     */
    function update_your_mark($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('your_mark',$params);
    }
    
    /*
     * function to delete your_mark
     */
    function delete_your_mark($id)
    {
        return $this->db->delete('your_mark',array('id'=>$id));
    }
}
